source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LBNConsultaCEP_Example', :exclusive => true do
  pod 'LBNConsultaCEP', :path => '../'
end

target 'LBNConsultaCEP_Tests', :exclusive => true do
  pod 'LBNConsultaCEP', :path => '../'

  pod 'Kiwi'
end
